//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 04:35:13 PM BRT 
//


package br.uff.mh.mestrado.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="maxCollectionSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxSubsetSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxCost" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="distribution" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="alfa" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="seed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="greedySeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="greedyRandomLoops" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="localSearchRandomLoops" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="graspRandomLoops" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pathRelinkingCandidateListMaxSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ls" type="{}lsList"/>
 *         &lt;element name="genetic" type="{}genetic"/>
 *         &lt;element name="graspTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="graspTargetMaxTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="graspTargetLoops" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="strategyHCMC" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyHCMCR" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyHCMCRAlfa" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyHCTNV" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyLS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyPRFor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyPRBack" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyPRForAndBack" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyGRASP" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyGRASPTarget" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strategyGenetic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxCollectionSize",
    "maxSubsetSize",
    "maxCost",
    "distribution",
    "alfa",
    "seed",
    "greedySeed",
    "greedyRandomLoops",
    "localSearchRandomLoops",
    "graspRandomLoops",
    "pathRelinkingCandidateListMaxSize",
    "ls",
    "genetic",
    "graspTarget",
    "graspTargetMaxTime",
    "graspTargetLoops",
    "strategyHCMC",
    "strategyHCMCR",
    "strategyHCMCRAlfa",
    "strategyHCTNV",
    "strategyLS",
    "strategyPRFor",
    "strategyPRBack",
    "strategyPRForAndBack",
    "strategyGRASP",
    "strategyGRASPTarget",
    "strategyGenetic"
})
@XmlRootElement(name = "config")
public class Config {

    protected int maxCollectionSize;
    protected int maxSubsetSize;
    protected int maxCost;
    protected double distribution;
    protected double alfa;
    protected int seed;
    protected int greedySeed;
    protected int greedyRandomLoops;
    protected int localSearchRandomLoops;
    protected int graspRandomLoops;
    protected int pathRelinkingCandidateListMaxSize;
    @XmlElement(required = true)
    protected LsList ls;
    @XmlElement(required = true)
    protected Genetic genetic;
    protected int graspTarget;
    protected int graspTargetMaxTime;
    protected int graspTargetLoops;
    protected boolean strategyHCMC;
    protected boolean strategyHCMCR;
    protected boolean strategyHCMCRAlfa;
    protected boolean strategyHCTNV;
    protected boolean strategyLS;
    protected boolean strategyPRFor;
    protected boolean strategyPRBack;
    protected boolean strategyPRForAndBack;
    protected boolean strategyGRASP;
    protected boolean strategyGRASPTarget;
    protected boolean strategyGenetic;

    /**
     * Gets the value of the maxCollectionSize property.
     * 
     */
    public int getMaxCollectionSize() {
        return maxCollectionSize;
    }

    /**
     * Sets the value of the maxCollectionSize property.
     * 
     */
    public void setMaxCollectionSize(int value) {
        this.maxCollectionSize = value;
    }

    /**
     * Gets the value of the maxSubsetSize property.
     * 
     */
    public int getMaxSubsetSize() {
        return maxSubsetSize;
    }

    /**
     * Sets the value of the maxSubsetSize property.
     * 
     */
    public void setMaxSubsetSize(int value) {
        this.maxSubsetSize = value;
    }

    /**
     * Gets the value of the maxCost property.
     * 
     */
    public int getMaxCost() {
        return maxCost;
    }

    /**
     * Sets the value of the maxCost property.
     * 
     */
    public void setMaxCost(int value) {
        this.maxCost = value;
    }

    /**
     * Gets the value of the distribution property.
     * 
     */
    public double getDistribution() {
        return distribution;
    }

    /**
     * Sets the value of the distribution property.
     * 
     */
    public void setDistribution(double value) {
        this.distribution = value;
    }

    /**
     * Gets the value of the alfa property.
     * 
     */
    public double getAlfa() {
        return alfa;
    }

    /**
     * Sets the value of the alfa property.
     * 
     */
    public void setAlfa(double value) {
        this.alfa = value;
    }

    /**
     * Gets the value of the seed property.
     * 
     */
    public int getSeed() {
        return seed;
    }

    /**
     * Sets the value of the seed property.
     * 
     */
    public void setSeed(int value) {
        this.seed = value;
    }

    /**
     * Gets the value of the greedySeed property.
     * 
     */
    public int getGreedySeed() {
        return greedySeed;
    }

    /**
     * Sets the value of the greedySeed property.
     * 
     */
    public void setGreedySeed(int value) {
        this.greedySeed = value;
    }

    /**
     * Gets the value of the greedyRandomLoops property.
     * 
     */
    public int getGreedyRandomLoops() {
        return greedyRandomLoops;
    }

    /**
     * Sets the value of the greedyRandomLoops property.
     * 
     */
    public void setGreedyRandomLoops(int value) {
        this.greedyRandomLoops = value;
    }

    /**
     * Gets the value of the localSearchRandomLoops property.
     * 
     */
    public int getLocalSearchRandomLoops() {
        return localSearchRandomLoops;
    }

    /**
     * Sets the value of the localSearchRandomLoops property.
     * 
     */
    public void setLocalSearchRandomLoops(int value) {
        this.localSearchRandomLoops = value;
    }

    /**
     * Gets the value of the graspRandomLoops property.
     * 
     */
    public int getGraspRandomLoops() {
        return graspRandomLoops;
    }

    /**
     * Sets the value of the graspRandomLoops property.
     * 
     */
    public void setGraspRandomLoops(int value) {
        this.graspRandomLoops = value;
    }

    /**
     * Gets the value of the pathRelinkingCandidateListMaxSize property.
     * 
     */
    public int getPathRelinkingCandidateListMaxSize() {
        return pathRelinkingCandidateListMaxSize;
    }

    /**
     * Sets the value of the pathRelinkingCandidateListMaxSize property.
     * 
     */
    public void setPathRelinkingCandidateListMaxSize(int value) {
        this.pathRelinkingCandidateListMaxSize = value;
    }

    /**
     * Gets the value of the ls property.
     * 
     * @return
     *     possible object is
     *     {@link LsList }
     *     
     */
    public LsList getLs() {
        return ls;
    }

    /**
     * Sets the value of the ls property.
     * 
     * @param value
     *     allowed object is
     *     {@link LsList }
     *     
     */
    public void setLs(LsList value) {
        this.ls = value;
    }

    /**
     * Gets the value of the genetic property.
     * 
     * @return
     *     possible object is
     *     {@link Genetic }
     *     
     */
    public Genetic getGenetic() {
        return genetic;
    }

    /**
     * Sets the value of the genetic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Genetic }
     *     
     */
    public void setGenetic(Genetic value) {
        this.genetic = value;
    }

    /**
     * Gets the value of the graspTarget property.
     * 
     */
    public int getGraspTarget() {
        return graspTarget;
    }

    /**
     * Sets the value of the graspTarget property.
     * 
     */
    public void setGraspTarget(int value) {
        this.graspTarget = value;
    }

    /**
     * Gets the value of the graspTargetMaxTime property.
     * 
     */
    public int getGraspTargetMaxTime() {
        return graspTargetMaxTime;
    }

    /**
     * Sets the value of the graspTargetMaxTime property.
     * 
     */
    public void setGraspTargetMaxTime(int value) {
        this.graspTargetMaxTime = value;
    }

    /**
     * Gets the value of the graspTargetLoops property.
     * 
     */
    public int getGraspTargetLoops() {
        return graspTargetLoops;
    }

    /**
     * Sets the value of the graspTargetLoops property.
     * 
     */
    public void setGraspTargetLoops(int value) {
        this.graspTargetLoops = value;
    }

    /**
     * Gets the value of the strategyHCMC property.
     * 
     */
    public boolean isStrategyHCMC() {
        return strategyHCMC;
    }

    /**
     * Sets the value of the strategyHCMC property.
     * 
     */
    public void setStrategyHCMC(boolean value) {
        this.strategyHCMC = value;
    }

    /**
     * Gets the value of the strategyHCMCR property.
     * 
     */
    public boolean isStrategyHCMCR() {
        return strategyHCMCR;
    }

    /**
     * Sets the value of the strategyHCMCR property.
     * 
     */
    public void setStrategyHCMCR(boolean value) {
        this.strategyHCMCR = value;
    }

    /**
     * Gets the value of the strategyHCMCRAlfa property.
     * 
     */
    public boolean isStrategyHCMCRAlfa() {
        return strategyHCMCRAlfa;
    }

    /**
     * Sets the value of the strategyHCMCRAlfa property.
     * 
     */
    public void setStrategyHCMCRAlfa(boolean value) {
        this.strategyHCMCRAlfa = value;
    }

    /**
     * Gets the value of the strategyHCTNV property.
     * 
     */
    public boolean isStrategyHCTNV() {
        return strategyHCTNV;
    }

    /**
     * Sets the value of the strategyHCTNV property.
     * 
     */
    public void setStrategyHCTNV(boolean value) {
        this.strategyHCTNV = value;
    }

    /**
     * Gets the value of the strategyLS property.
     * 
     */
    public boolean isStrategyLS() {
        return strategyLS;
    }

    /**
     * Sets the value of the strategyLS property.
     * 
     */
    public void setStrategyLS(boolean value) {
        this.strategyLS = value;
    }

    /**
     * Gets the value of the strategyPRFor property.
     * 
     */
    public boolean isStrategyPRFor() {
        return strategyPRFor;
    }

    /**
     * Sets the value of the strategyPRFor property.
     * 
     */
    public void setStrategyPRFor(boolean value) {
        this.strategyPRFor = value;
    }

    /**
     * Gets the value of the strategyPRBack property.
     * 
     */
    public boolean isStrategyPRBack() {
        return strategyPRBack;
    }

    /**
     * Sets the value of the strategyPRBack property.
     * 
     */
    public void setStrategyPRBack(boolean value) {
        this.strategyPRBack = value;
    }

    /**
     * Gets the value of the strategyPRForAndBack property.
     * 
     */
    public boolean isStrategyPRForAndBack() {
        return strategyPRForAndBack;
    }

    /**
     * Sets the value of the strategyPRForAndBack property.
     * 
     */
    public void setStrategyPRForAndBack(boolean value) {
        this.strategyPRForAndBack = value;
    }

    /**
     * Gets the value of the strategyGRASP property.
     * 
     */
    public boolean isStrategyGRASP() {
        return strategyGRASP;
    }

    /**
     * Sets the value of the strategyGRASP property.
     * 
     */
    public void setStrategyGRASP(boolean value) {
        this.strategyGRASP = value;
    }

    /**
     * Gets the value of the strategyGRASPTarget property.
     * 
     */
    public boolean isStrategyGRASPTarget() {
        return strategyGRASPTarget;
    }

    /**
     * Sets the value of the strategyGRASPTarget property.
     * 
     */
    public void setStrategyGRASPTarget(boolean value) {
        this.strategyGRASPTarget = value;
    }

    /**
     * Gets the value of the strategyGenetic property.
     * 
     */
    public boolean isStrategyGenetic() {
        return strategyGenetic;
    }

    /**
     * Sets the value of the strategyGenetic property.
     * 
     */
    public void setStrategyGenetic(boolean value) {
        this.strategyGenetic = value;
    }

}
