//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 04:35:13 PM BRT 
//


package br.uff.mh.mestrado.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for genetic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="genetic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="loop" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="populationSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="classASize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="classBSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="classCSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "genetic", propOrder = {
    "loop",
    "populationSize",
    "classASize",
    "classBSize",
    "classCSize"
})
public class Genetic {

    protected int loop;
    protected int populationSize;
    protected int classASize;
    protected int classBSize;
    protected int classCSize;

    /**
     * Gets the value of the loop property.
     * 
     */
    public int getLoop() {
        return loop;
    }

    /**
     * Sets the value of the loop property.
     * 
     */
    public void setLoop(int value) {
        this.loop = value;
    }

    /**
     * Gets the value of the populationSize property.
     * 
     */
    public int getPopulationSize() {
        return populationSize;
    }

    /**
     * Sets the value of the populationSize property.
     * 
     */
    public void setPopulationSize(int value) {
        this.populationSize = value;
    }

    /**
     * Gets the value of the classASize property.
     * 
     */
    public int getClassASize() {
        return classASize;
    }

    /**
     * Sets the value of the classASize property.
     * 
     */
    public void setClassASize(int value) {
        this.classASize = value;
    }

    /**
     * Gets the value of the classBSize property.
     * 
     */
    public int getClassBSize() {
        return classBSize;
    }

    /**
     * Sets the value of the classBSize property.
     * 
     */
    public void setClassBSize(int value) {
        this.classBSize = value;
    }

    /**
     * Gets the value of the classCSize property.
     * 
     */
    public int getClassCSize() {
        return classCSize;
    }

    /**
     * Sets the value of the classCSize property.
     * 
     */
    public void setClassCSize(int value) {
        this.classCSize = value;
    }

}
